server:
  port: 8086

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stock_master?useSSL=false&characterEncoding=utf-8&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 1000
    database: 0

logging:
  file: /logs/stock_service.log
  level:
    org.springfromework.web: info
    org.hibernate: error
